# Generated by Django 2.1.5 on 2019-02-15 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthDate', models.DateField(default='1212-12-12')),
                ('phoneNumber', models.CharField(default='', max_length=9)),
                ('address', models.CharField(default='', max_length=100)),
                ('postCode', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('canViewOthers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=False)),
                ('m_period1', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period2', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period3', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period4', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period5', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period6', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period7', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period8', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period9', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('m_period10', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period1', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period2', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period3', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period4', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period5', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period6', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period7', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period8', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period9', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('t_period10', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period1', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period2', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period3', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period4', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period5', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period6', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period7', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period8', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period9', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('w_period10', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period1', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period2', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period3', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period4', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period5', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period6', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period7', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period8', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period9', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('th_period10', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period1', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period2', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period3', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period4', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period5', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period6', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period7', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period8', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period9', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
                ('f_period10', models.CharField(choices=[('Free', 'Free'), ('Absent', 'Absent'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Art', 'Art'), ('English', 'English'), ('Design Technology', 'Design Technology'), ('', '')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('schoolmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index.SchoolMember')),
                ('role', models.CharField(choices=[('CL', 'Cleaner'), ('T', 'Teacher'), ('TE', 'Test')], default='TE', max_length=2)),
            ],
            bases=('index.schoolmember',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('schoolmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index.SchoolMember')),
                ('parentEmail', models.EmailField(blank=True, max_length=254)),
            ],
            bases=('index.schoolmember',),
        ),
    ]
